services:
  # Inngest Dev Server (Background Processing)
  inngest:
    image: inngest/inngest:latest
    container_name: ticket-classifier-inngest
    command: "inngest dev -u http://host.docker.internal:8000/api/inngest --no-discovery"
    ports:
      - "8288:8288"
    environment:
      - INNGEST_LOG_LEVEL=info
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8288/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ticket-classifier

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ticket-classifier-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ticket-classifier

networks:
  ticket-classifier:
    driver: bridge

volumes:
  qdrant_storage:
    driver: local
